# Generated by Django 4.2.4 on 2023-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleball', '0003_customuser_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='league_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_playing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced_beginner', 'Advanced Beginner'), ('intermediate', 'Intermediate'), ('high_intermediate', 'High Intermediate'), ('advanced', 'Advanced'), ('high_advanced', 'High Advanced')], default='Beginner', max_length=20),
        ),
    ]
